In [ ]:
import numpy as np
x=np.array([[1,0,1,0],[1,0,0,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 1]])

In [ ]:
y=np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
# prompt: create derivative for above function
def sigmoid_derivative(x):
  return x*(1-x)

In [ ]:
#i/p,epoch,learning rate,o/p
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [ ]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [ ]:
for i in range(epoch):
    # Forward pass
    hidden_layer_input = np.dot(x, wh) + bh
    hidden_layer_activation = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_activation, wo) + bo
    predicted_output = sigmoid(output_layer_input)

    # Backpropagation
    error = y - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(wo.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_activation)

    # Updating Weights and Biases
    wo += hidden_layer_activation.T.dot(d_predicted_output) * lr
    bo += np.sum(d_predicted_output, axis=0, keepdims=True) * lr
    wh += x.T.dot(d_hidden_layer) * lr
    bh += np.sum(d_hidden_layer, axis=0, keepdims=True) * lr

# After the training, you can use the 'predicted_output' for evaluation.


In [ ]:
predicted_output

array([[0.97054995],
       [0.05169581],
       [0.96711084]])

In [ ]:
# prompt: import tensorflow print version

import tensorflow as tf
tf.__version__


'2.15.0'

In [ ]:
mnist = tf.keras.datasets.fashion_mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-1.2665663 ,  0.5424058 ,  0.6642422 ,  0.6408826 ,  0.31284285,
         0.26048437, -0.1081464 ,  0.17181653, -0.34989822,  0.8287029 ]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

1.7804868

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.5339 - accuracy: 0.8121
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3995 - accuracy: 0.8550
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3689 - accuracy: 0.8657
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3458 - accuracy: 0.8732
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3324 - accuracy: 0.8773


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.3507 - accuracy: 0.8730 - 604ms/epoch - 2ms/step


[0.3507104814052582, 0.8730000257492065]